SELECT
LOCATION, COUNT(DISTINCT(ORDER_ID)) AS orders, 
ROUND(SUM(ORDER_TOTAL),0) AS revenue, 
COUNT(DISTINCT(CUSTOMER_ID)) AS customers,  
ROUND(SUM(ORDER_TOTAL)/NULLIF(COUNT(DISTINCT(ORDER_ID)),0),0) AS avg_order_value, ROUND(SUM(ORDER_TOTAL)/NULLIF(COUNT(DISTINCT(CUSTOMER_ID)),0),0) AS avg_order_value_per_customer

FROM OL_ORDERS
LEFT JOIN {{ ref('ol_stores') }} ON LOCATION_ID = STORE_ID
GROUP BY 1